### ISSUE TITLE
Example images?

### ISSUE THREAD

**Issue by typeshige** [ideak/leafclusterer#1]
Hi, could you provide some images of it in action?

Is it easy to swap out images ourselves?

**Comment by ideak** [comment]
Hi,

Not sure what exactly you're interested in, but here is some sample:
http://i.imgur.com/sv46l.png

The cluster icons are easy to replace, you just need to provide an image link for each cluster size.

**Comment by netconstructor** [comment]
Thanks - so it is essentially just like the google maps version.

How complicated do you think it would be to animate markers to split appart from their cluster to their assocuating locations before "destroy" gets called?

Just like on redfin.com

Chris
