### ISSUE TITLE
addEventListener IE7

### ISSUE THREAD

**Issue by Mathbl** [ideak/leafclusterer#2]
Hello!

Great start on this addon! I hate having to do workaround for old (shitty) browser like IE7, but I did test leafclusterer on IE7 and it didn't work, as IE7 use attachEvent instead of addEventListener. 

I know leaflet use a workaround method to go over this issue, would it be easy to implement in leafclusterer? 

Thank you !

**Comment by ideak** [comment]
Hi,

unfortunately I don't have an IE7 to experiment with, but I would
accept patches if you figure out the way to fix this.

--Imre

On Thu, Mar 22, 2012 at 5:38 PM, HooliganQC
reply@reply.github.com
wrote:

**Comment by spospy** [comment]
Hi Imre,

I came across the same problem. I fixed it by changing the lines starting at 639:

```
this.container_.addEventListener(
  "click",
  function() {
    cluster.onClick_(cluster);
  },
  false);
```

to:

```
if (this.container_.addEventListener) {
    this.container_.addEventListener(
      "click",
      function() {
        cluster.onClick_(cluster);
      },
      false);
} else if(this.container_.attachEvent) {
    this.container_.attachEvent(
      "onclick",
      function() {
        cluster.onClick_(cluster);
      });
}
```

This seems to have resolved the issue for me.

**Comment by Mathbl** [comment]
Hi spospy!

Yeah it works well, good job on that one! :)

**Comment by ideak** [comment]
spospy: thanks! Do you care sending this patch formatted with 'git format-patch' with some explanation in the commit message?

**Comment by ideak** [comment]
Fix from spospy merged.
