### ISSUE TITLE
Displaying clusters over 1000

### ISSUE THREAD

**Issue by mriddle** [ideak/leafclusterer#6]
I found a minor issue when using your library and rendering large clusters with over 1000 markers. The background styling repeats from the bottom and right sides
Example: http://i44.tinypic.com/f02042.png

**Comment by ideak** [comment]
Hi, thanks for the report. I will try to reproduce it. So far I have used the library with about 1800 markers, but haven't seen this issue. But now that I think of it they were not in the same cluster.. Will get back when I found the issue.
