### ISSUE TITLE
new LeafClusterer(map); fails?

### ISSUE THREAD

**Issue by HOTwheel** [ideak/leafclusterer#9]
I just wanted to start with leafclusterer, but even the initialization fails?!
In every browser I get a: Uncaught ReferenceError: L is not defined - leafclusterer.js:580
The leaflet map works as expected.

``` javascript
<script type="text/javascript">
        var map = new L.Map('map');
        var cloudmadeUrl = 'http://{s}.tile.cloudmade.com/MY_API_KEY/22677/256/{z}/{x}/{y}.png',
            cloudmadeAttribution = 'Map data &copy; 2011 OpenStreetMap contributors, Imagery &copy; 2011 CloudMade',
            cloudmade = new L.TileLayer(cloudmadeUrl, { maxZoom: 18, attribution: cloudmadeAttribution });
        map.setView(new L.LatLng(51.5, -0.09), 13).addLayer(cloudmade);;
        var clusterer = new LeafClusterer(map);    // <------- fails
        var markers = [];
    </script>
```

**Comment by Mathbl** [comment]
Are you sure the leaflet.js librairy is loading? You need leaflet to use leafclusterer so if L is not defined, it seems that the library is not loaded correctly.

**Comment by HOTwheel** [comment]
Yes it loaded correctly but I was the fault. I loaded the libraries in the worng order (LeafClusterer prior to Leaflet). Did cost me some time to recognize this ^^
Sorry for the fuss.

**Comment by nkanayan** [comment]
yeah, order is important, thx
